/**
 * The generated-file class on TypeScript: every declaration in a file that marks itself
 * generated, or below a directory an applied convention row names as generated, is
 * retained, because a generator owns the file and a deletion there is undone at the next
 * generation.
 */

import type { DetectorInput, Evidence } from "./exempt.ts";
import type { SourceFiles } from "./source-files.ts";

/** The generated-code header, matched against each line of a leading comment. */
const HEADER_LINE = /^\/\/ Code generated .* DO NOT EDIT\.$/u;

/** The documentation tag `@generated` as a word of a comment. */
const GENERATED_TAG = /(?<![\w@$])@generated(?![\w$-])/u;

/** The comments before a text's first token, a leading hashbang line skipped. */
function leadingComments(text: string): readonly string[] {
  const comments: string[] = [];
  let at = text.startsWith("\uFEFF") ? 1 : 0;
  if (text.startsWith("#!", at)) {
    const end = text.indexOf("\n", at);
    at = end === -1 ? text.length : end + 1;
  }
  for (;;) {
    while (at < text.length && /\s/u.test(text.charAt(at))) {
      at++;
    }
    if (text.startsWith("//", at)) {
      const end = text.slice(at).search(/[\r\n\u2028\u2029]/u);
      const stop = end === -1 ? text.length : at + end;
      comments.push(text.slice(at, stop));
      at = stop;
    } else if (text.startsWith("/*", at)) {
      const end = text.indexOf("*/", at + 2);
      if (end === -1) {
        return comments;
      }
      comments.push(text.slice(at, end + 2));
      at = end + 2;
    } else {
      return comments;
    }
  }
}

/** The detail a file's leading comments mark it generated by, or undefined where they mark nothing. */
export function generatedByComment(text: string): string | undefined {
  const comments = leadingComments(text);
  if (comments.some((one) => one.split(/\r?\n/u).some((line) => HEADER_LINE.test(line)))) {
    return "generated by the header line its leading comments hold";
  }
  if (comments.some((one) => GENERATED_TAG.test(one))) {
    return "generated by the @generated tag its leading comments hold";
  }
  return undefined;
}

/**
 * Every own file of one project that is generated, by its path below the target root,
 * with the detail a retention in it names: its leading comments' mark, else the row
 * naming its directory as generated.
 */
export function generatedFilesOf(
  files: SourceFiles,
  byRow: ReadonlyMap<string, string>,
): ReadonlyMap<string, string> {
  const found = new Map<string, string>();
  for (const [path, file] of files.byPath) {
    const row = byRow.get(path);
    const detail =
      generatedByComment(file.text) ??
      (row === undefined
        ? undefined
        : `generated below a directory the convention row ${row} names`);
    if (detail !== undefined) {
      found.set(path, detail);
    }
  }
  return found;
}

/** The generated-file detector, recording each file's first line. */
export function generatedFile<Brand>(input: DetectorInput<Brand>): readonly Evidence[] {
  const generated = input.generated;
  if (generated === undefined || generated.size === 0) {
    return [];
  }
  return input.held.symbols.flatMap((symbol): Evidence[] => {
    const detail = generated.get(symbol.position.path);
    return symbol.kind === "file" || detail === undefined
      ? []
      : [{ id: symbol.id, detail, site: { path: symbol.position.path, line: 1, column: 1 } }];
  });
}
