import { rmSync } from "node:fs";
import { afterAll, describe, expect, it } from "vitest";
import { emitterInputOf, findingsOf } from "../__test-helpers__/emitter-input.ts";
import { writeProject } from "../__test-helpers__/projects.ts";
import { generatedByComment } from "./generated-file.ts";
import { resolve } from "./resolve.ts";

/** A project whose installed framework names `.nuxt` as the directory it generates. */
const PROJECT: Readonly<Record<string, string>> = {
  "package.json":
    '{ "name": "@example/app", "type": "module", "devDependencies": { "nuxt": "4.999.0" } }\n',
  "node_modules/nuxt/package.json": '{ "name": "nuxt", "version": "4.999.0" }\n',
  ".nuxt/routes.ts": 'export const routeName = "index";\n\nexport const unusedGenerated = 0;\n',
  "util.ts": "export const used = 1;\n\nexport const unusedWritten = 2;\n",
  "pages/index.ts":
    'import { routeName } from "../.nuxt/routes.js";\nimport { used } from "../util.js";\n\nconsole.log(routeName, used);\n',
};

const roots: string[] = [];
afterAll(() => {
  for (const root of roots) {
    rmSync(root, { recursive: true, force: true });
  }
});

/** The project analyzed with `analysis.generated_files` set to one value; the framework package itself is unused. */
function analyzed(generatedFiles: "exclude" | "include"): ReturnType<typeof emitterInputOf> {
  const root = writeProject(PROJECT);
  roots.push(root);
  const repository = JSON.stringify({
    target: { kind: "application" },
    analysis: { generated_files: generatedFiles },
  });
  const { config } = resolve({ repository, repositoryLabel: "deadset.json" });
  return emitterInputOf(root, config);
}

describe("the generated-file class", () => {
  it("retains each declaration below a directory an applied row names as generated, and reports the one beside it", () => {
    const input = analyzed("exclude");

    expect(
      findingsOf(input)
        .filter((finding) => finding.code !== "DS1601")
        .map((finding) => `${finding.code} ${finding.symbol.name}`),
    ).toEqual(["DS1001 unusedWritten"]);
    expect(
      input.swept.retained.map(
        (record) =>
          `${record.class} ${record.site.path}:${String(record.site.line)} ${record.detail}`,
      ),
    ).toEqual([
      "generated-file .nuxt/routes.ts:1 generated below a directory the convention row nuxt names",
    ]);
  });

  it("reports a declaration in a generated file once generated files are included, marked as one no edit may act on", () => {
    const found = findingsOf(analyzed("include"))
      .filter((finding) => finding.code !== "DS1601")
      .map(
        ({ code, symbol, generated, fixability }) =>
          `${code} ${symbol.name} generated=${String(generated)} ${fixability}`,
      );

    expect(found).toEqual([
      "DS1001 unusedGenerated generated=true none",
      "DS1001 unusedWritten generated=false deletable",
    ]);
  });
});

describe("an export a generated file references only inside itself", () => {
  /** The redundant-export findings of a project whose generated file reads its own export. */
  function redundantExports(generatedFiles: "exclude" | "include"): readonly string[] {
    const root = writeProject({
      "package.json": '{ "name": "@example/app", "type": "module", "main": "./main.ts" }\n',
      "schema_pb.ts":
        "// @generated by the schema compiler\n\nexport const inner = 1;\n\nexport const outer = inner + 1;\n",
      "main.ts": 'import { outer } from "./schema_pb.js";\n\nconsole.log(outer);\n',
    });
    roots.push(root);
    const { config } = resolve({
      repository: JSON.stringify({
        target: { kind: "application" },
        analysis: { generated_files: generatedFiles },
      }),
      repositoryLabel: "deadset.json",
    });
    return findingsOf(emitterInputOf(root, config))
      .filter((finding) => finding.code === "DS1104")
      .map(({ symbol, generated }) => `${symbol.name} generated=${String(generated)}`);
  }

  it("is not reported as a redundant export keyword under the default", () => {
    expect(redundantExports("exclude")).toEqual([]);
  });

  it("is reported as one, marked generated, once generated files are included", () => {
    expect(redundantExports("include")).toEqual(["inner generated=true"]);
  });
});

describe("generatedByComment", () => {
  it("reads the header line in a line comment or a block comment before the first token", () => {
    expect(
      [
        "// Code generated by protoc-gen-es. DO NOT EDIT.\nexport {};\n",
        "#!/usr/bin/env node\n// Code generated by a tool. DO NOT EDIT.\r\nexport {};\n",
        "/* eslint-disable */\n/*\n// Code generated by a tool. DO NOT EDIT.\n*/\nexport {};\n",
      ].map(generatedByComment),
    ).toEqual(Array(3).fill("generated by the header line its leading comments hold"));
  });

  it("reads the @generated tag as a word of a leading comment", () => {
    expect(
      ["/**\n * @generated SignedSource<<0>>\n */\nexport {};\n", "// @generated\n"].map(
        generatedByComment,
      ),
    ).toEqual(Array(2).fill("generated by the @generated tag its leading comments hold"));
  });

  it("marks nothing for a mark after the first token, a header that differs, or a longer tag", () => {
    expect(
      [
        "export {};\n// Code generated by a tool. DO NOT EDIT.\n",
        "// Code generated by a tool. Do not edit.\n",
        "//Code generated by a tool. DO NOT EDIT.\n",
        "// @generatedBy a tool\n",
        "// email@generated.example\n",
        "const tag = '@generated';\n",
      ].map(generatedByComment),
    ).toEqual(Array(6).fill(undefined));
  });
});

describe("a file whose leading comments mark it generated", () => {
  it("retains its declarations, names the mark, and reports one past the first token", () => {
    const root = writeProject({
      "package.json": '{ "name": "@example/app", "type": "module", "main": "./main.ts" }\n',
      "wire.ts":
        "// Code generated by a tool. DO NOT EDIT.\n\nexport const usedWire = 1;\n\nexport const unusedWire = 2;\n",
      "tagged.ts": "/** @generated */\nexport const usedTag = 1;\n\nexport const unusedTag = 2;\n",
      "late.ts":
        "export const usedLate = 1;\n\n// Code generated by a tool. DO NOT EDIT.\nexport const unusedLate = 2;\n",
      "main.ts":
        'import { usedLate } from "./late.js";\nimport { usedTag } from "./tagged.js";\nimport { usedWire } from "./wire.js";\n\nconsole.log(usedLate, usedTag, usedWire);\n',
    });
    roots.push(root);
    const { config } = resolve({
      repository: JSON.stringify({ target: { kind: "application" } }),
      repositoryLabel: "deadset.json",
    });
    const input = emitterInputOf(root, config);

    expect(findingsOf(input).map((finding) => `${finding.code} ${finding.symbol.name}`)).toEqual([
      "DS1001 unusedLate",
    ]);
    expect(
      input.swept.retained.map((record) => `${record.class} ${record.site.path} ${record.detail}`),
    ).toEqual([
      "generated-file tagged.ts generated by the @generated tag its leading comments hold",
      "generated-file wire.ts generated by the header line its leading comments hold",
    ]);
  });
});
